// TODO 1 IMPORTE O ARQUIVO DE CONFIGURAÇÃO .env

// TODO 2 IMPORTE OS MODULOS EXPRESS, HTTP, CORS

// TODO 3 DEFINA AS VARIAVEIS DE CONFIGURAÇÃO: HOST, PORT

// TODO 4 CÓDIFIQUE O SCRIPT QUE RENDERIZE ARQUIVOS STATICOS

// TODO 5 CÓDIFIQUE O SCRIPT QUE INICIAR O SERVIDOR HTTP

// TODO 6 EXPORTE O OBJETO app

// APÓS A FINALIZAÇÃO DE TODOS OS PASSOS, EXECUTE O app.js com o comando node app.js