// TODO 1 IMPORTE O MODULO DA OPENAI

// TODO 2 IMPORTE O OBJETO APP

// TODO 3 CRIE A VARIAVEL ONDE O TOKEN SERÁ AMAZENADO

// TODO 4 CÓDIFIQUE O SCRIPT DE CONFIGURAÇÃO DA OPENAI

// TODO 5 CRIE O SCRIPT DE ROTEAMENTO ONDE A API RECEBERÁ DADOS DO CLIENTE

// TODO 6 CRIE UMA FUNÇÃO QUE FAÇA REQUISIÇÃO NA OPENAI USANDO COMO BASE O MODULO DA OPENAI